CREATE TABLE users
(
    id       INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
    username VARCHAR(30) NOT NULL UNIQUE,
    email    VARCHAR(30) NOT NULL UNIQUE,
    pass     VARCHAR(30) NOT NULL,
    gender   VARCHAR(6)  NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

